version: '2'
services:
  virtuoso:
    build:
      context: ./
      dockerfile: ./virtuoso/Dockerfile
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "https://soilproject.org/onto"
    ports:
      - "8890:8890"
  # lode:
  #   build:
  #     context: ./lode
  #     dockerfile: Dockerfile
  #     args:
  #        LODE_EXTERNAL_URL: "http://localhost:9090/lode"
  #        # WEBVOWL_EXTERNAL_URL: "http://visualdataweb.de/webvowl/#iri="
  #        # useHTTPs: "false"
  #        useHTTPs: "true"
  #   # container_name: lode
  #   ports:
  #     - "9090:8080"
  #     # - 8080:8080/tcp
  lode:
    build: ./lode
    ports:
      - "9090:8080"
  lodview:
    build: ./lodview
    ports:
      - "8080:8080"
  lodlive:
    build: ./lodlive
    ports:
      - "80:80"
