version: '2'
services:
  main:
    build: ./src
  virtuoso:
    # image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    # environment:
    #   SPARQL_UPDATE: "true"
    # volumes:
    #   - ./data/virtuoso:/data
    build: ./virtuoso
    ports:
      - "8890:8890"
  lode:
    build: ./lode
    ports:
      - "9090:8080"
  lodview:
    build: ./lodview
    ports:
      - "8080:8080"
